#!/bin/sh
set -e

#
# Downloads Workman's three self-hosted variable typefaces from Google Fonts
# and regenerates src/styles/fonts.scss.
#
# Google already serves per-script subsets of the variable fonts as woff2, so
# unlike the old Open Sans/Quicksand pipeline this needs no fonttools step —
# we keep Google's unicode-range split, which means a browser only downloads
# the scripts it actually renders.
#
# Files are named <Family>-<subset>_<blake2b-8>.woff2 so Vite can hash them and
# vite.config.ts's createFontMatcher can find the latin faces to preload.
#

err_report() {
	echo "Error on line $(caller)" >&2
}

trap err_report ERR

cd "$(dirname "$0")/.."

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
TEMP_FOLDER="./.font-download-temp"

mkdir -p "$TEMP_FOLDER"

echo ""
echo "###################################################"
echo "# Fetch @font-face declarations"
echo "###################################################"
echo ""

fetch_css() {
	family="$1"
	name="$2"
	echo "  $name"
	curl -sS -A "$UA" \
		"https://fonts.googleapis.com/css2?family=${family}&display=swap" \
		-o "${TEMP_FOLDER}/${name}.css" \
		--max-time 60
}

fetch_css "Space+Grotesk:wght@300..700" "SpaceGrotesk"
fetch_css "Inter:wght@100..900" "Inter"
fetch_css "JetBrains+Mono:wght@100..800" "JetBrainsMono"

echo ""
echo "###################################################"
echo "# Download woff2 files and write fonts.scss"
echo "###################################################"
echo ""

TEMP_FOLDER="$TEMP_FOLDER" python3 - <<'PY'
import hashlib
import os
import pathlib
import re
import subprocess

TEMP = pathlib.Path(os.environ['TEMP_FOLDER'])
OUT = pathlib.Path('src/assets/fonts')
OUT.mkdir(parents=True, exist_ok=True)

# family -> (temp css name, output basename, subsets worth shipping)
FAMILIES = [
    ('SpaceGrotesk', {'latin', 'latin-ext', 'vietnamese'}),
    ('Inter', {'latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'greek-ext', 'vietnamese'}),
    ('JetBrainsMono', {'latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'vietnamese'}),
]

BLOCK = re.compile(r'/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{(.*?)\}', re.S)

stale = {p.name for p in OUT.glob('*.woff2')}
faces = []

for base, keep in FAMILIES:
    css = (TEMP / f'{base}.css').read_text()
    for subset, body in BLOCK.findall(css):
        if subset not in keep:
            continue
        url = re.search(r'url\((https://[^)]+\.woff2)\)', body).group(1)
        urange = re.search(r'unicode-range:\s*([^;]+);', body).group(1).strip()
        weight = re.search(r'font-weight:\s*([^;]+);', body).group(1).strip()
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)

        data = subprocess.run(
            ['curl', '-sSL', '--max-time', '60', url],
            capture_output=True, check=True,
        ).stdout
        digest = hashlib.blake2b(data, digest_size=4).hexdigest()
        fname = f'{base}-{subset}_{digest}.woff2'
        (OUT / fname).write_bytes(data)
        stale.discard(fname)
        faces.append((family, fname, weight, urange))
        print(f'  {fname:<46} {len(data) / 1024:7.1f} KB')

for name in sorted(stale):
    (OUT / name).unlink()
    print(f'  removed stale {name}')

lines = [
    '// Workman self-hosted variable typefaces.',
    '// Space Grotesk (display / wordmark), Inter (UI + body), JetBrains Mono (data + micro-labels).',
    '// Generated by scripts/fonts-download.sh — do not edit by hand.',
    '',
    "$font-files-path: '@/assets/fonts/';",
    '',
]
for family, fname, weight, urange in faces:
    lines += [
        '@font-face {',
        f"  font-family: '{family}';",
        f"  src: url($font-files-path + '{fname}') format('woff2-variations'),",
        f"       url($font-files-path + '{fname}') format('woff2');",
        '  font-style: normal;',
        f'  font-weight: {weight};',
        '  font-display: swap;',
        f'  unicode-range: {urange};',
        '}',
        '',
    ]
pathlib.Path('src/styles/fonts.scss').write_text('\n'.join(lines))
print(f'\n  wrote src/styles/fonts.scss with {len(faces)} faces')
PY

rm -r "$TEMP_FOLDER"

echo ""
echo "Done. Remember to check the preload matcher in vite.config.ts still matches."
